 version: '3'
 
 services:
  telegrampolling:
    image: telegrampolling
    build:
      context: .
    networks:
      - monitoramento-network
      
      
 networks:
        monitoramento-network:
            driver: bridge